name: CI

on: push

jobs:
  check_format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.12.2'
      - uses: actions/cache@v2
        env:
          cache-name: cache-elixir-deps
        with:
          path: |
            deps
            _build

          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            {{ runner.os }}-build-${{ env.cache-name }}
            {{ runner.os }}-build-
            {{ runner.os }}-
      - name: Fetch Deps
        run: mix deps.get
      - name: ==> Check Format
        run: mix format --check-formatted 

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.12.2'
      - uses: actions/cache@v2
        env:
          cache-name: cache-elixir-deps
        with:
          path: |
            deps
            _build

          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            {{ runner.os }}-build-${{ env.cache-name }}
            {{ runner.os }}-build-
            {{ runner.os }}-
      - name: Fetch Deps
        run: mix deps.get
      - name: ==> Credo validations
        run: mix credo --strict         